name: Auto Comment
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Auto comment pull request
        uses: bubkoo/auto-comment@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: "\U0001F44B @{{ author }} Thanks for creating a PR!\n\
            \nUntil this PR is ready for review, you can include the [WIP] tag in\
            \ its title, or leave it as a github draft.\n\nPlease make sure it is\
            \ compliant with our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines).\
            \ In particular, be sure it checks the boxes listed below.\n- [ ] PR has\
            \ an interpretable title.\n- [ ] PR links to Github issue with mention\
            \ `Closes #XXXX` (see our documentation on [PR structure](https://nilearn.github.io/stable/development.html#pr-structure))\n\
            - [ ] Code is PEP8-compliant (see our documentation on [coding style](https://nilearn.github.io/stable/development.html#coding-style))\n\
            - [ ] Changelog or what's new entry in `doc/changes/latest.rst` (see our\
            \ documentation on [PR structure](https://nilearn.github.io/stable/development.html#pr-structure))\n\
            \nFor new features:\n- [ ] There is at least one unit test per new function\
            \ / class (see our documentation on [testing](https://nilearn.github.io/stable/development.html#tests))\n\
            - [ ] The new feature is demoed in at least one relevant example.\n\n\
            For bug fixes:\n- [ ] There is at least one test that would fail under\
            \ the original bug conditions.\n\nWe will review it as quick as possible,\
            \ feel free to ping us with questions if needed.\n"
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
