name: DocumentationBuilder
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  BROWSER: /usr/bin/firefox
  DISPLAY: :99.0
  FORCE_COLOR: true
  HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  MIN_PYTHON_VERSION: '3.9'
  NILEARN_DATA: /home/runner/work/nilearn/nilearn/nilearn_data
jobs:
  build_docs:
    defaults:
      run:
        shell: bash -el {0}
    needs:
      - get_data
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Merge with upstream
        run: ./build_tools/github/merge_upstream.sh
      - id: measurement-3
        name: Record Measurement After Merge with upstream
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Merge with upstream
          task: get-measurement
      - name: Install apt packages
        run: "sudo -E apt-get -yq update\nsudo -E apt-get -yq --no-install-suggests\
          \ --no-install-recommends install \\\n    dvipng texlive-latex-base texlive-latex-extra\n"
      - id: measurement-5
        name: Record Measurement After Install apt packages
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install apt packages
          task: get-measurement
      - name: Key for cache based on month number
        run: date +%m > month_num;
      - id: measurement-7
        name: Record Measurement After Key for cache based on month number
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Key for cache based on month number
          task: get-measurement
      - name: Get data from the get_data job
        uses: actions/cache@v4
        with:
          key: data_cache-${{ github.workflow }}_ref-${{ github.ref }}_run-${{ github.run_number
            }}_attempt-${{ github.run_attempt }}
          path: nilearn_data
          restore-keys: 'data_cache-${{ github.workflow }}_ref-${{ github.ref }}_run-${{
            github.run_number }}

            '
      - name: Set up display server for virtual browser
        run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
      - id: measurement-10
        name: Record Measurement After Set up display server for virtual browser
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Set up display server for virtual browser
          task: get-measurement
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}
      - name: Download build type
        uses: actions/download-artifact@v4
        with:
          name: build_type
      - name: Install tox
        run: uv tool install tox --with=tox-uv --with=tox-gh-actions
      - id: measurement-15
        name: Record Measurement After Install tox
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install tox
          task: get-measurement
      - name: Show tox config
        run: tox c
      - id: measurement-17
        name: Record Measurement After Show tox config
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Show tox config
          task: get-measurement
      - id: build-docs
        name: Build docs
        run: "set -o pipefail;\nexport PATTERN=$(cat pattern.txt)\ntox run \\\n  \
          \  --colored yes \\\n    --list-dependencies \\\n    -e doc -- $(cat build.txt)\
          \ 2>&1 | tee log.txt;\n"
      - id: measurement-19
        name: Record Measurement After Build docs
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build docs
          task: get-measurement
      - if: always()
        name: Check for unreplaced argument in docstrings
        run: './build_tools/github/fill_doc_check.sh

          cat doc/tmp/doc_check.txt

          '
      - id: measurement-21
        name: Record Measurement After Check for unreplaced argument in docstrings
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check for unreplaced argument in docstrings
          task: get-measurement
      - if: steps.build-docs.outcome == 'success'
        name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: doc/_build/html
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  build_type:
    needs:
      - check_skip_flags
      - validate_cff
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Merge with upstream
        run: ./build_tools/github/merge_upstream.sh
      - id: measurement-3
        name: Record Measurement After Merge with upstream
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Merge with upstream
          task: get-measurement
      - env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        name: Check if we are doing a full or partial build
        run: ./build_tools/github/build_type.sh
      - id: measurement-5
        name: Record Measurement After Check if we are doing a full or partial build
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check if we are doing a full or partial build
          task: get-measurement
      - name: Verify build type
        run: 'echo "PATTERN = $(cat pattern.txt)"

          echo "BUILD = $(cat build.txt)"

          '
      - id: measurement-7
        name: Record Measurement After Verify build type
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Verify build type
          task: get-measurement
      - name: Upload build.txt and pattern.txt
        uses: actions/upload-artifact@v4
        with:
          name: build_type
          overwrite: true
          path: 'build.txt

            pattern.txt

            '
          retention-days: 1
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  check_skip_flags:
    name: Check skip flags
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check head git commit message
        run: "headCommitMsg=$(git show -s --format=%s)\nif [[ $headCommitMsg == *\"\
          [skip doc]\"* ]]; then\n    echo \"skipping doc build\"\n    exit 1\nfi\n"
      - id: measurement-3
        name: Record Measurement After Check head git commit message
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check head git commit message
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  deploy_on_main:
    if: ${{ contains(fromJSON('["push", "workflow_dispatch", "schedule", "release"]'),
      github.event_name)}}
    needs:
      - build_docs
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        name: Add SSH key
        run: 'mkdir -p ~/.ssh

          ssh-keyscan github.com >> ~/.ssh/known_hosts

          echo "${{ secrets.ACTIONS_SSH_DEPLOY }}" > ~/.ssh/github_actions

          chmod 600 ~/.ssh/github_actions

          ssh-agent -a $SSH_AUTH_SOCK > /dev/null

          ssh-add ~/.ssh/github_actions

          '
      - id: measurement-3
        name: Record Measurement After Add SSH key
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Add SSH key
          task: get-measurement
      - uses: actions/download-artifact@v4
        with:
          name: doc
          path: doc/_build/html
      - id: deploy-type
        name: Identify deploy type
        run: "if ${{ contains(fromJSON('[\"release\"]'), github.event_name)}}; then\n\
          \    echo \"DEPLOY_TYPE=stable\" >> $GITHUB_OUTPUT\nelse\n    echo \"DEPLOY_TYPE=dev\"\
          \ >> $GITHUB_OUTPUT\nfi\n"
      - id: measurement-6
        name: Record Measurement After Identify deploy type
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Identify deploy type
          task: get-measurement
      - env:
          COMMIT_SHA: ${{ github.event.head_commit.id }}
          DEPLOY_TYPE: ${{ steps.deploy-type.outputs.DEPLOY_TYPE }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        name: deploy
        run: 'git config --global user.email "actions@github.com"

          git config --global user.name "GitHub actions"

          ./build_tools/github/deploy_doc.sh

          '
      - id: measurement-8
        name: Record Measurement After deploy
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: deploy
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  get_data:
    defaults:
      run:
        shell: bash -el {0}
    if: github.repository == 'nilearn/nilearn'
    needs:
      - build_type
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}
      - name: Install packages
        run: 'python -m pip install --user --upgrade pip setuptools

          python -m pip install .

          '
      - id: measurement-4
        name: Record Measurement After Install packages
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install packages
          task: get-measurement
      - name: Download build type
        uses: actions/download-artifact@v4
        with:
          name: build_type
      - id: build-type
        name: Verify build type
        run: echo "build=$(cat build.txt)" >> $GITHUB_OUTPUT
      - id: measurement-7
        name: Record Measurement After Verify build type
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Verify build type
          task: get-measurement
      - name: Determine if we will use cached data
        run: ./build_tools/github/determine_restore_data.sh
      - id: measurement-9
        name: Record Measurement After Determine if we will use cached data
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Determine if we will use cached data
          task: get-measurement
      - id: cache-key
        name: Get cache key
        run: "if [[ $(cat restore.txt) == \"true\" ]]; then\n    echo \"restore=true\"\
          \ >> $GITHUB_OUTPUT\nfi\n"
      - id: measurement-11
        name: Record Measurement After Get cache key
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get cache key
          task: get-measurement
      - name: Key for cache based on month number
        run: date +%m > month_num;
      - id: measurement-13
        name: Record Measurement After Key for cache based on month number
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Key for cache based on month number
          task: get-measurement
      - id: restore-previous-run
        if: steps.cache-key.outputs.restore == 'true'
        name: Get cache from a previous attempts on this PR or branch
        uses: actions/cache/restore@v4
        with:
          key: data_cache-${{ github.workflow }}_ref-${{ github.ref }}_run-${{ github.run_number
            }}_attempt-${{ github.run_attempt }}
          path: nilearn_data
          restore-keys: 'data_cache-${{ github.workflow }}_ref-${{ github.ref }}_run-${{
            github.run_number }}

            data_cache-${{ github.workflow }}_ref-${{ github.ref }}

            '
      - id: restore-previous-full-build
        if: ${{ steps.build-type.outputs.build == 'html-strict' && steps.cache-key.outputs.restore
          == 'true' && steps.restore-previous-run.outputs.cache-hit != 'true' }}
        name: Get data from a previous successful run for full builds
        uses: actions/cache@v4
        with:
          key: data_cache-${{ github.workflow }}_month-${{ hashFiles('month_num')
            }}
          path: nilearn_data
      - if: ${{ steps.cache-key.outputs.restore == 'true' && steps.restore-previous-run.outputs.cache-hit
          != 'true' && steps.restore-previous-full-build.outputs.cache-hit != 'true'
          }}
        name: Get data for reports from a previous successful run
        uses: actions/cache@v4
        with:
          key: data_cache-${{ github.workflow }}_month-${{ hashFiles('month_num')
            }}
          path: 'nilearn_data/adhd

            nilearn_data/development_fmri

            nilearn_data/difumo_atlases

            nilearn_data/ds000030

            nilearn_data/fiac_nilearn.glm

            nilearn_data/icbm152_2009

            nilearn_data/miyawaki2008

            nilearn_data/msdl_atlas

            nilearn_data/oasis1

            nilearn_data/schaefer_2018

            nilearn_data/yeo_2011

            '
      - name: Get data
        run: 'echo "Download data required for building reports in doc"

          python doc/get_data_examples.py


          echo "Download data required for this doc build type"

          BUILD_TYPE=$(cat build.txt)

          python doc/get_data_examples.py $BUILD_TYPE

          '
      - id: measurement-18
        name: Record Measurement After Get data
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get data
          task: get-measurement
      - if: always()
        name: Save cache to pass to build_docs job
        uses: actions/cache/save@v4
        with:
          key: data_cache-${{ github.workflow }}_ref-${{ github.ref }}_run-${{ github.run_number
            }}_attempt-${{ github.run_attempt }}
          path: nilearn_data
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  validate_cff:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
