name: Benchmark test suite
on:
  push:
    branches:
      - main

jobs:
  check_gha_workflow:
    if: github.repository == 'nilearn/nilearn'
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install --requirement maint_tools/requirements.txt
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Collect and plot test suite run time
        run: python maint_tools/check_gha_workflow.py ${{ secrets.GITHUB_TOKEN }}
      - id: measurement-6
        name: Record Measurement After Collect and plot test suite run time
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Collect and plot test suite run time
          task: get-measurement
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: test_runs_timing_outputs
          path: maint_tools/*_runs_timing.*
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
