name: Redirect circleci artifacts
on:
  push:
    branches:
      - main

jobs:
  circleci_artifacts_redirector_job:
    name: Run CircleCI artifacts redirector
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: GitHub Action step
        uses: scientific-python/circleci-artifacts-redirector-action@v1
        with:
          api-token: ${{ secrets.CIRCLE_CI_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: host_docs
          job-title: Check the HTML doc here!
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
permissions: read-all
