name: test on nightly dependencies
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  FORCE_COLOR: true
jobs:
  nightly:
    if: github.repository == 'nilearn/nilearn'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: check-commit-msg
        name: For PRs check if commit message contains [test nightly]
        run: "set -e -x\ncommit_msg=$(git log -2 --format=oneline);\nif [ \"$GITHUB_REF_NAME\"\
          \ == \"main\" ]; then\n    echo \"run test on nightly releases of nilearn\
          \ dependencies\"\n    echo \"skip=false\" >> $GITHUB_OUTPUT\nelse\n    if\
          \ [[ $commit_msg == *\"[test nightly]\"* ]]; then\n        echo \"run test\
          \ on nightly releases of nilearn dependencies\"\n        echo \"skip=false\"\
          \ >> $GITHUB_OUTPUT\n    else\n        echo \"skip test on nightly releases\
          \ of nilearn dependencies\"\n        echo \"skip=true\" >> $GITHUB_OUTPUT\n\
          \    fi;\nfi;\n"
      - id: measurement-3
        name: Record Measurement After For PRs check if commit message contains [test
          nightly]
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: For PRs check if commit message contains [test nightly]
          task: get-measurement
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - if: steps.check-commit-msg.outputs.skip == 'false'
        name: Install tox
        run: uv tool install tox --with=tox-uv --with=tox-gh-actions
      - id: measurement-7
        name: Record Measurement After Install tox
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install tox
          task: get-measurement
      - continue-on-error: true
        id: nightly
        if: steps.check-commit-msg.outputs.skip == 'false'
        name: Run test suite
        run: tox run --list-dependencies -e nightly -- nilearn
      - id: measurement-9
        name: Record Measurement After Run test suite
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run test suite
          task: get-measurement
      - if: success() || failure()
        name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: nightly_report.html
          path: report.html
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        if: ${{ github.event_name != 'pull_request' && steps.nightly.outcome != 'success'
          }}
        name: Create issue
        uses: JasonEtco/create-an-issue@v2.9.2
        with:
          filename: .github/nightly_failure.md
          search_existing: open
          update_existing: true
      - if: ${{ steps.check-commit-msg.outputs.skip == 'false' && steps.nightly.outcome
          != 'success' }}
        name: Return failure
        run: exit 1
      - id: measurement-13
        name: Record Measurement After Return failure
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Return failure
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
