name: test minimal version of each dependency
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  FORCE_COLOR: true
jobs:
  test_min_install:
    if: github.repository == 'nilearn/nilearn'
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }} and ${{ matrix.min_dep
      }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for building Nilearn
        run: 'python -m pip install --upgrade pip setuptools

          pip install ${{ matrix.min_dep }}

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies for building Nilearn
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies for building Nilearn
          task: get-measurement
      - name: Install nilearn
        run: pip install .[plotting,plotly,test]
      - id: measurement-6
        name: Record Measurement After Install nilearn
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install nilearn
          task: get-measurement
      - name: Run tests
        run: pytest --pyargs nilearn --cov=nilearn
      - id: measurement-8
        name: Record Measurement After Run tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      fail-fast: false
      matrix:
        min_dep:
          - joblib==1.2.0
          - nibabel==5.2.0
          - numpy==1.22.4
          - pandas==2.2.0
          - scikit-learn==1.4.0
          - scipy==1.8.0
          - matplotlib==3.3.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.9'
