name: Update authors
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  update_authors:
    if: github.repository == 'nilearn/nilearn'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout nilearn
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          allow-prereleases: false
          python-version: '3.12'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip ruamel.yaml

          python -m pip install .[plotting]

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Update AUTHORS.rst and doc/changes/names.rst
        run: python maint_tools/citation_cff_maint.py
      - id: measurement-6
        name: Record Measurement After Update AUTHORS.rst and doc/changes/names.rst
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Update AUTHORS.rst and doc/changes/names.rst
          task: get-measurement
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          body: done via this [GitHub Action](https://github.com/${{ github.repository_owner
            }}/nilearn/blob/main/.github/workflows/update_authors.yml)
          commit-message: update AUTHORS.rst and doc/changes/names.rst
          delete-branch: true
          title: '[BOT] update AUTHORS.rst and doc/changes/names.rst'
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
